# Workshop #3: Multivariable Calculus

In [2]:
#importing libraries
import numpy as np
import sympy as sp
import scipy.optimize as opt

## Problem 1
Find the critical points of the function $f(x, y) = x^2 + y^4 - 4xy$ by using first partial derivatives. Then use second partial derivatives to establish whether each critical point is a local minimum, a local maximum, or a saddle point.

In [3]:
# Define the variables and the function
x, y = sp.symbols('x y', real =True)
f = sp.Function('f',real=True)
F = sp.Function('F',real=True)

f = x**2 + y**4 -4*x*y
# Differentiate
f_x = f.diff(x)
f_y = f.diff(y)

eq_1 = sp.Eq(f_x, 0)
eq_2 = sp.Eq(f_y, 0)

# Find critical points
crit_pts = sp.solve((eq_1, eq_2), (x, y))

# Classifying the critical points
print(f'Critical points are {crit_pts[0]} and {crit_pts[1]}')

# Getting the second derivatives
f_xx = f.diff(x, 2)
f_yy = f.diff(y, 2)
f_xy = f.diff(x, y)


# # Working with the first critical point
dict_val = {x:crit_pts[0][0], y:crit_pts[0][1]}
d = f_xx.subs(dict_val) * f_yy.subs(dict_val) - (f_xy.subs(dict_val))**2
print(f'd = {d} < 0 and we conclude that {crit_pts[0]} is a saddle point')

# Working with the second critical point
dict_val2 = {x:crit_pts[1][0], y:crit_pts[1][1]}
d2 = f_xx.subs(dict_val2) * f_yy.subs(dict_val2) - (f_xy.subs(dict_val2))**2
print(f'd = {d2} >0 and we conclude that {crit_pts[1]} is a local minimum')

# Working with the third critical point
dict_val3 = {x:crit_pts[1][1], y:crit_pts[1][1]}
d3 = f_xx.subs(dict_val3) * f_yy.subs(dict_val3) - (f_xy.subs(dict_val3))**2
print(f'd = {d3} >0 and we conclude that {crit_pts[2]} is a local minimum')


Critical points are (0, 0) and (-2*sqrt(2), -sqrt(2))
d = -16 < 0 and we conclude that (0, 0) is a saddle point
d = 32 >0 and we conclude that (-2*sqrt(2), -sqrt(2)) is a local minimum
d = 32 >0 and we conclude that (2*sqrt(2), sqrt(2)) is a local minimum


## Problem 2
Using the **Gradient Descent Method** with initial approximation $\mathbf{x}_0 = (0, 0)$, find the minimum point and the minimum value of the function $g(x, y) = (1 - x + x^2)\cdot e^{y^2} + (1 - y + y^2)\cdot e^{x^2}$.

In [4]:
# Define variables and functions
x, y = sp.symbols('x y')
g = sp.Function('g',real=True)
G = sp.Function('G',real=True)
g = (1-x+x**2)*sp.exp(y**2)+ (1-y+y**2) * sp.exp(x**2)

g_x = g.diff(x)
g_y = g.diff(y)

# Define the numpy functions
g = sp.lambdify([x,y],g)
g_x = sp.lambdify([x,y],g_x)
g_y = sp.lambdify([x,y],g_y)

def func(x_k):
    x = x_k[0]
    y = x_k[1]
    return (g(x,y))

def grad(x_k):
    x = x_k[0]
    y = x_k[1]

    return np.array([g_x(x,y),
                     g_y(x,y)])

# x0 = np.array([0, 0])
# gradient_descent(func, grad, x0, alpha=0.01)

# Running the Gradient Descent Method
def gradient_descent(g, grad, x0, alpha = 0.01, mode = 'min', max_iter = 1000, tol = 1e-6):
    
    # initialize the sequence
    k = 0
    xk = x0

    if mode == 'max':
        alpha = -alpha
    while k < max_iter and np.linalg.norm(grad(xk),2) > tol: # loop until we do not have a solution

        xk = xk - alpha * grad(xk) #calculate the new iteration
        k = k + 1  #increment the iteration number
      
    return xk, g(xk), np.linalg.norm(grad(xk), 2), k


In [5]:
x0 = np.array([0, 0])

gradient_descent (func, grad, x0, max_iter=1100)

(array([0.2778799, 0.2778799]), 1.7270110514248864, 9.643289486085021e-07, 387)

## Problem 3
On a certain workday, the *rate*, in tons per hour, at which unprocessed gravel arrives at a gravel processing plant is modeled by $G(t) = 90 + 45\cdot \cos⁡\left(\frac{t^2}{18}\right)$, where $t$ is measured in hours and $0 \leqslant t \leqslant 8$. At the beginning of the workday, $t = 0$, the plant has 500 tons of unprocessed gravel. During the hours of operation, $0 \leqslant t \leqslant 8$, the plant processes gravel at a constant rate $P(t) = 100$ tons per hour.
* Find the total amount of unprocessed gravel that arrives at the plant during the hours of operation on this workday.
* Is the amount of unprocessed gravel at the end of the workday (t=8) greater or smaller than amount of gravel at the beginning of the workday?

In [6]:
# Define variable and functions
t = sp.symbols('t', positive=True)

G = 90+45*sp.cos(t**2/18)
P = 100

# First bullet point
ans_1 = sp.integrate(G, (t,0,8))
print(f'*During the workday a total of {round(ans_1.evalf(),2)} tons of gravel arrives at the plant')

# Second bullet point
Q = 500 + sp.integrate(G, (t,0,8)) - sp.integrate (P, (t,0,8))
print(f'*At the end of the workday, there will be {round(Q.evalf(),2)} tons of unprocessed gravel at th eplant, which is more than the amount at the beginning of the workday')



*During the workday a total of 825.55 tons of gravel arrives at the plant
*At the end of the workday, there will be 525.55 tons of unprocessed gravel at th eplant, which is more than the amount at the beginning of the workday


## Problem 4
Solve the system of equations:
\begin{equation}
\left\{
\begin{array}{rcl}
x - 2y + 3z &=& -1\\
3x + 2y - 5z &=& 3\\
2x - 5y + 2z &=& 0
\end{array}
\right.
\end{equation}

using **Gradient Descent Method** applied to a function of the kind $f(x) = \|A\mathbf{x} - b\|_2^2$ where $A\mathbf{x} = b$ is the matrix equation that corresponds to the system, and $\| \cdot \|_2$ is the Euclidean norm.


In [7]:
# Define variables and matrices
A = sp.Matrix([[1, -2, 3],
               [3, 2, -5],
               [2, -5, 2]])

b = sp.Matrix([-1, 3, 0])

x,y,z, X = sp.symbols('x y z X', real=True)

X = sp.Matrix([x,y,z])

# Define the function and derivatives
f = ((A*X - b).norm())**2

dfdx = sp.lambdify([x,y,z], f.diff(x))
dfdy = sp.lambdify([x,y,z], f.diff(y))
dfdz = sp.lambdify([x,y,z], f.diff(z))

f = sp.lambdify([x,y,z],f)


# Define the NumPy function

def func(xk):
    x = xk[0]
    y = xk[1]
    z = xk[2]

    return f(x,y,z)

def grad(xk):
  x = xk[0]
  y = xk[1]
  z = xk[2]

  return np.array([dfdx(x,y,z),
                   dfdy(x,y,z),
                   dfdz(x,y,z)])

# Running the Gradient Descent Method
xk = np.array([6,-1,1])

gradient_descent(func, grad, xk)


(array([ 0.26086976, -0.08695635, -0.4782607 ]),
 1.530250529911669e-13,
 9.830335419305582e-07,
 509)

## Problem 5

[Use Gradient Descent Method] Four people are typing two paragraphs of text. The first paragraph uses elementary vocabulary, while the second paragraph contains some more advanced words. The number of typos that the people make are labeled by 𝑥, for the first paragraph, and 𝑦, for the second paragraph. Data collected is given in the accompanying table:

| x 	 | y 	|
|---	 |---	|
| 1 	 | 4 	|
| 3 	 | 5 	|
| 4 	 | 6 	|
| 5 	 | 8 	|


We will build a model to predict the number of typos $y$ in the second text based on the number of typos in the first test. To do this, we use least-squares regression, an approach similar to the one we used for systems. For every number of observed typos $x_i$ for the first text, we have a corresponding number $y_i$ of observed typos for the second text. Our model $\hat{y_i} = f(x_i)$ will make a prediction of the number of typos on the second text. Most often, the observed number of typos $y_i$ and the predicted number of typos $\hat{y_i}$ will not be equal.
Let us label each such discrepancy in values by $d_i$, in other words:

\begin{align}
d_i = observed_i - predicted_i = y_i - \hat{y_i}
\end{align}


We call these discrepancies residuals. The goal now is to choose a model which will minimize the total sum of the squares of the residuals, i.e. a model which will make the overall discrepancy between the observed data and the predictions based on it as small as possible. Note that the form of the residuals depends on the choice of the model. For example, choosing a linear model $\hat{y_i}=a+bx$, we have prediction $\hat{y_i}=a+bx$, so the residuals become:

\begin{align}
d^2 = (y-\hat{y})^2 = (y-a-bx)^2
\end{align}

The total sum of the squares of the residuals is then $\sum_{i=1}^n d_i^2 = \sum_{i=1}^n (y_i-a-bx_i)^2$. This allows us to define the function $f$ that we need to minimize in order to build the model as:

\begin{align}
f(a,b) = \sum_{i=1}^n(y_i-a-bx_i)^2
\end{align}

By minimizing this function, we find the values for the coefficients $a$ and $b$ in the model that minimize the discrepancy between the data and the type of model we chose to work with.

*a)* Build a linear model for the data: $\hat{y}=a+bx$. Then make a prediction about the number of typos $y$ a person would make when typing the second text if they have made $x=2$ typos when typing the first text. **Use your own gradient_descent function.**

*b)* Build a quadratic model for the data: $\hat{y}=a+bx+cx^2$. Then make a prediction about the same person from part a). **Use the minimizer BFGS.**

**a) Linear model:**

In [8]:
# Define variables and matrices
A = sp.Matrix([[1, 1], [1, 3], [1, 4], [1, 5]])
y = sp.Matrix([4, 5, 6, 8])
a, b, X = sp.symbols('a b X', real=True)
X = sp.Matrix([a, b])

# Define the function f
f = sp.Function('f', real=True)
f = ((y-A*X).norm())**2

# Define the numpy function f
dfda = sp.lambdify([a,b], f.diff(a))
dfdb = sp.lambdify([a,b], f.diff(b))

f = sp.lambdify([a,b], f)

def func(xk):
    a = xk[0]
    b = xk[1]

    return (f(a,b))

def grad_f(xk):
    a = xk[0]
    b = xk[1] 

    return np.array([dfda(a,b),
                   dfdb(a,b)])

x0 = np.array([0, 2])
gradient_descent(func, grad_f, x0, max_iter=2000)


(array([2.68571354, 0.94285734]),
 0.971428571428955,
 9.946473346286155e-07,
 1167)

**b) Quadratic model:**

In [9]:
# Define variables and matrices
A = sp.Matrix([[1, 1, 1], [1, 3, 9], [1, 4, 16], [1, 5, 25]])
y = sp.Matrix([4, 5, 6, 8])
a, b, c, X = sp.symbols('a b c X')
X = sp.Matrix([a, b, c])

# Define the function f
f = ((y-A*X).norm())**2 
f
# Define the numpy function f
dfda = sp.lambdify([a,b,c], f.diff(a))
dfdb = sp.lambdify([a,b,c], f.diff(b))
dfdc = sp.lambdify([a,b,c], f.diff(c))

f = sp.lambdify([a,b,c], f)

def func(xk):
    a = xk[0]
    b = xk[1]
    c = xk[2]
  

    return (f(a,b,c))

x0 = np.array([0, 2, 2])

In [13]:
# Run the BFGS algorithm
opt_output=opt.minimize(func, x0, method='BFGS')
opt_output

      fun: 0.03636363636421916
 hess_inv: array([[ 2.28983046, -1.6420376 ,  0.24871486],
       [-1.6420376 ,  1.41535663, -0.23194833],
       [ 0.24871486, -0.23194833,  0.03961032]])
      jac: array([9.40635800e-07, 1.73458830e-06, 9.85711813e-06])
  message: 'Optimization terminated successfully.'
     nfev: 40
      nit: 8
     njev: 10
   status: 0
  success: True
        x: array([ 4.39999929, -0.65454448,  0.27272709])

In [15]:
x_y_z = opt_output.x
print(f'ŷ = {x_y_z[0]}{x_y_z[1]}*x + {x_y_z[2]}*x^2')
x=2
print(f'ŷ = {x_y_z[0]}{x_y_z[1]}*{x} + {x_y_z[2]}*x^2 = {x_y_z[0] + x_y_z[1]*x + x_y_z[2]*x**2}')

ŷ = 4.399999294713105-0.6545444759812679*x + 0.27272708723891087*x^2
ŷ = 4.399999294713105-0.6545444759812679*2 + 0.27272708723891087*x^2 = 4.181818691706213
